In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import time as tm
import random as rnd
from IPython import display
%matplotlib inline

# Задача 1


In [ ]:
# Не понял как выполнить

# Задача 2

In [ ]:
a = np.arange(2, 75, step=1)
a[a%2 !=0]=-1
a[a%2 !=0]

# Задача 3

In [2]:
a = np.arange(2, 75, step=1)
b=  np.arange(2, 75, step=4)
newarr = np.setdiff1d(a,b, assume_unique=True)#Найдите в документации функцию, которая удаляет из одного массива элементы, которые есть в другом.
print(newarr)


[ 3  4  5  7  8  9 11 12 13 15 16 17 19 20 21 23 24 25 27 28 29 31 32 33
 35 36 37 39 40 41 43 44 45 47 48 49 51 52 53 55 56 57 59 60 61 63 64 65
 67 68 69 71 72 73]


# Задача 4

In [8]:
a = np.random.uniform(low=10, high=100, size=(5,5))# Создайте случайную квадратную матрицу случайного размера от 10 до 100.
Max_a = a.max()#Найдите максимум 
print('Максимальное значение:{}'.format(Max_a))
Sum_a =a.sum()#Найдите сумму элементов.
print('Сумма элементов:{}'.format(Sum_a))

Максимальное значение:97.66639126472643
Сумма элементов:1456.8867107679005


In [9]:
#Замените максимальное значение на -1. 
a[a==a.max()]=-1
a

array([[11.56664436, 16.22965447, 62.77130621, 45.11125593, 68.32324905],
       [53.12389367, 69.91555636, 50.93180173, 46.73194534, 72.6029109 ],
       [90.59344544, 80.07428397, 74.14552096, 95.66259591, -1.        ],
       [58.28523003, 77.10734217, 42.24442361, 61.6568142 , 41.15735049],
       [18.75750126, 63.28741756, 89.88351028, 22.60241445, 46.45425114]])

# Задача 5

In [26]:
def replace_pass(x_in):
    x = x_in.copy()
    if np.sum(np.isnan(x)) == n * k:
        x[np.isnan(x)] = 0
        print(0)
    else:
        xmean = np.nanmean(x)
        x[np.isnan(x)] = xmean
    print('Среднее значение {}'.format(xmean))
    return x


In [27]:
n = 5
k = 5
p = 5
x = np.random.random((n, k))
for i in range(5):
    x[rnd.randint(0, n - 1), rnd.randint(0, k - 1)] = np.nan
print(x)
print(replace_pass(x))

[[       nan        nan 0.15383824 0.49585958 0.91569924]
 [0.58004801 0.10765633 0.32238488 0.92438715        nan]
 [0.40702195 0.42090133 0.30301765        nan 0.29393314]
 [0.32642629 0.53051475 0.1687053  0.46056405 0.68358002]
 [0.38719767 0.45551624 0.34480298        nan 0.6571906 ]]
Среднее значение 0.44696226960407587
[[0.44696227 0.44696227 0.15383824 0.49585958 0.91569924]
 [0.58004801 0.10765633 0.32238488 0.92438715 0.44696227]
 [0.40702195 0.42090133 0.30301765 0.44696227 0.29393314]
 [0.32642629 0.53051475 0.1687053  0.46056405 0.68358002]
 [0.38719767 0.45551624 0.34480298 0.44696227 0.6571906 ]]


# Задание 6

In [40]:
def normalization(x1):
    x = x1.copy()
    xmax = x.max()
    x = x/xmax
    return x

In [51]:
p = 8
x = np.random.randint(0, 100, size=(5, 5))
norm_df=normalization(x)
print('Нормализованный массив:\n{}'.format(norm_df))

Нормализованный массив:
[[0.87755102 0.19387755 0.59183673 0.70408163 0.65306122]
 [0.6122449  0.40816327 0.60204082 0.80612245 0.95918367]
 [0.15306122 0.28571429 0.01020408 0.89795918 0.89795918]
 [0.37755102 0.19387755 1.         0.64285714 0.24489796]
 [0.19387755 0.47959184 0.83673469 0.84693878 1.        ]]


# Задание 7

In [52]:
np.save('Text_in_np', norm_df)

In [53]:
df = np.load('Text_in_np.npy')
df

array([[0.87755102, 0.19387755, 0.59183673, 0.70408163, 0.65306122],
       [0.6122449 , 0.40816327, 0.60204082, 0.80612245, 0.95918367],
       [0.15306122, 0.28571429, 0.01020408, 0.89795918, 0.89795918],
       [0.37755102, 0.19387755, 1.        , 0.64285714, 0.24489796],
       [0.19387755, 0.47959184, 0.83673469, 0.84693878, 1.        ]])

# Задание 8

In [57]:
x = np.random.randint(1, 100, size=(6, 6))
print(f'Исходный массив:\n {x}')
p = 100
r = np.abs(x - p)
mr = r.min()
i, j = np.where(r == mr)
print(f'Ближайший к {p} элемент равен {x[i, j]}, его индексы: {i} и {j}.')

Исходный массив:
 [[33 68 56 74 91  6]
 [98 16  4 53 21 45]
 [ 4 33 89 68 35 85]
 [90 16 18 54 68 12]
 [15 27 76 18  2 51]
 [55 36 27 40 78 80]]
Ближайший к 100 элемент равен [98], его индексы: [1] и [0].


# Задание 9

# Задание 10

In [67]:
def sort_matrix(x, k):
    return x[x[:,k].argsort()]

In [82]:
k=5
x = np.random.randint(1, 100, size=(5, 10))
print(f'Исходный массив:\n {x}')
y = sort_matrix(x, k)
print(f'Отсортированный по столбцу {k} массив:\n {y}')

Исходный массив:
 [[ 7 11 34 75 68 24 36 11  4 73]
 [ 6 49 90  4 56 51 28 10 38  4]
 [79 11 66 71 28 21 88 52 23  9]
 [94  2  2 69 78 54 26  6 27 54]
 [71 50 14 46 91 34 81 45 87 22]]
Отсортированный по столбцу 5 массив:
 [[79 11 66 71 28 21 88 52 23  9]
 [ 7 11 34 75 68 24 36 11  4 73]
 [71 50 14 46 91 34 81 45 87 22]
 [ 6 49 90  4 56 51 28 10 38  4]
 [94  2  2 69 78 54 26  6 27 54]]


# Задание 11

In [83]:

def chessboard(k):
    return np.tile(a, (k//2, k//2))

In [85]:

k = 8
a = [[1, 0], [0, 1]]
b = chessboard(k)
b

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])